---

version: "3.2"

services:
  sdk:
    build:
      context: .
      args:
        UID: "${UID}"
        GID: "${UID}"
    container_name: rtbhouse-php-sdk
    volumes:
      - ./src/:/home/apps/code/src
      - ./tests/:/home/apps/code/tests
