---

version: "3.2"

services:
  example:
    build:
      context: .
      args:
        UID: "${UID}"
        GID: "${UID}"
    container_name: rtbhouse-php-sdk-example
    volumes:
      - ./config.php/:/home/apps/code/config.php
      - ./example.php/:/home/apps/code/example.php
      - ./composer.json/:/home/apps/code/composer.json
